export default [
    {
        "_id": 123,
        "topic": "EDM",
        "userName": "Ultra",
        "handle": "@ultra",
        "time": "2h",
        "image": "../../images/ultra_icon.jpeg",
        "title": "Ultra Miami 2023 all set with Top tier DJs - Garrix, Zedd, etc.",
        "tuit": "Ultra returns with Ultra Miami 2023! Get your tickets now!!! GA Premium Sold out. VIP Premium 90% sold out.",
        "liked": true,
        "likes": 7942,
        "replies": 582,
        "retuits": 720,
        "disliked": false,
        "dislikes": 172
    },
    {
        "_id": 234,
        "topic": "News",
        "userName": "New York Times",
        "handle": "@nyt",
        "time": "2h",
        "image": "../../images/nyt_icon.png",
        "title": "People tend to listen EDM over indie Pop, 2023 surveys says.",
        "tuit": "EDM >>>> Indie POP : 2023 Survey Says. What are your thoughts on this?",
        "liked": false,
        "likes": 561,
        "replies": 1042,
        "retuits": 389,
        "disliked": true,
        "dislikes": 629
    },
    {
        "_id": 345,
        "topic": "POP",
        "userName": "The ChainSmokers",
        "handle": "@tcs",
        "time": "4d",
        "image": "../../images/tcs_profile.jpeg",
        "title": "So far so good album by @tcs is topping the POP charts on Spotify.",
        "tuit": "And we're back with So Far So Good - Solo Mission being my fav!! Go give a listen",
        "liked": true,
        "likes": 947,
        "replies": 640,
        "retuits": 872,
        "disliked": false,
        "dislikes": 103
    }
];